import type {
  BusinessSettings,
  PortfolioItem,
  Review,
  ReviewAggregates,
  SalonService,
} from '../types'

const hours = {
  open: '09:00',
  close: '20:00',
  closed: false,
}

export const defaultBusinessSettings: BusinessSettings = {
  businessName: 'Grace Hair Beauty',
  phone: '+13178503001',
  email: 'plbahoure2993@gmail.com',
  address: {
    street: '955 Baden Manor Dr',
    city: 'Indianapolis',
    state: 'IN',
    zip: '46217',
  },
  hours: {
    monday: hours,
    tuesday: hours,
    wednesday: hours,
    thursday: hours,
    friday: hours,
    saturday: hours,
    sunday: hours,
  },
  socialLinks: {
    instagram: 'https://www.instagram.com/ghbeauty24?igsh=MTM0bGxnMzF1OGI0Zw==',
    facebook: 'https://www.facebook.com/GraceHairBeauty01/',
    tiktok: 'https://www.tiktok.com/@ghbeauty24?_r=1&_t=ZT-96PlSWucAbW',
  },
  googleMapsUrl: 'https://www.google.com/search?kgmid=%2Fg%2F11yytfkdj8&q=Grace+hair+beauty',
  googleReviewUrl: 'https://www.google.com/search?kgmid=%2Fg%2F11yytfkdj8&q=Grace+hair+beauty',
  announcementBanner: null,
  bookingNotice: 'We confirm all appointments within 24 hours.',
}

export const mockServices: SalonService[] = [
  // ── African Braids ──────────────────────────────────────────────────
  {
    serviceId: 'svc-african-braids',
    name: 'African Braids',
    category: 'african-braids',
    subcategory: 'specialty-braids',
    description: 'Traditional African braiding with clean parts, lasting hold, and careful scalp care.',
    startingPrice: 18000,
    priceUnit: 'cents',
    durationMinutes: 240,
    imageUrl: '/services/african-braids.webp',
    featured: true,
    active: true,
    bookingCount: 145,
  },
  {
    serviceId: 'svc-knotless-braids',
    name: 'Knotless Braids',
    category: 'african-braids',
    subcategory: 'knotless-braids',
    description: 'Lightweight knotless braids with a natural lay and reduced scalp tension.',
    startingPrice: 21999,
    priceUnit: 'cents',
    durationMinutes: 300,
    imageUrl: '/services/knotless-braids-wavy-ends.webp',
    imagePosition: 'center 18%',
    featured: true,
    active: true,
    bookingCount: 187,
  },
  {
    serviceId: 'svc-box-braids',
    name: 'Box Braids',
    category: 'african-braids',
    subcategory: 'box-braids',
    description: 'Classic box braids with clean square parts, lightweight feel, and beautiful length.',
    startingPrice: 16500,
    priceUnit: 'cents',
    durationMinutes: 240,
    imageUrl: '/services/box-braids.webp',
    featured: true,
    active: true,
    bookingCount: 163,
  },
  {
    serviceId: 'svc-box-braids-styled',
    name: 'Styled Box Braids',
    category: 'african-braids',
    subcategory: 'box-braids',
    description: 'Box braids styled into an elegant updo or design for a polished, finished look.',
    startingPrice: 18000,
    priceUnit: 'cents',
    durationMinutes: 240,
    imageUrl: '/services/box-braids-styled.webp',
    featured: false,
    active: true,
    bookingCount: 43,
  },
  {
    serviceId: 'svc-senegalese-twist',
    name: 'Senegalese Twist',
    category: 'african-braids',
    subcategory: 'senegalese-twists',
    description: 'Classic senegalese twists with a smooth finish, natural look, and lasting hold.',
    startingPrice: 18000,
    priceUnit: 'cents',
    durationMinutes: 210,
    imageUrl: '/services/senegalese-twist.webp',
    featured: true,
    active: true,
    bookingCount: 91,
  },
  {
    serviceId: 'svc-senegalese-twist-colors',
    name: 'Senegalese Twist Colors',
    category: 'african-braids',
    subcategory: 'senegalese-twists',
    description: 'Vibrant senegalese twists with color blending for a bold, eye-catching protective style.',
    startingPrice: 20000,
    priceUnit: 'cents',
    durationMinutes: 270,
    imageUrl: '/services/senegalese-twist-colors.webp',
    featured: true,
    active: true,
    bookingCount: 67,
  },
  {
    serviceId: 'svc-fulani-braids',
    name: 'Fulani Braids',
    category: 'african-braids',
    subcategory: 'fulani-braids',
    description: 'Traditional fulani braids with delicate cornrow patterns and a refined protective finish.',
    startingPrice: 19000,
    priceUnit: 'cents',
    durationMinutes: 240,
    imageUrl: '/services/fulani-braids.webp',
    featured: true,
    active: true,
    bookingCount: 98,
  },
  {
    serviceId: 'svc-miracle-knot',
    name: 'Miracle Knot Hairstyle',
    category: 'african-braids',
    subcategory: 'specialty-braids',
    description: 'A stunning knotted style that blends artistry and protection for a truly unique look.',
    startingPrice: 21000,
    priceUnit: 'cents',
    durationMinutes: 300,
    imageUrl: '/services/miracle-knot-hairstyle.webp',
    featured: true,
    active: true,
    bookingCount: 47,
  },
  {
    serviceId: 'svc-crochet-braids',
    name: 'Crochet Braids',
    category: 'african-braids',
    subcategory: 'crochet-braids',
    description: 'Versatile crochet styles with efficient install time and beautiful movement.',
    startingPrice: 9999,
    priceUnit: 'cents',
    durationMinutes: 150,
    imageUrl: '/services/crochet-hairstyle.webp',
    featured: false,
    active: true,
    bookingCount: 54,
  },
  {
    serviceId: 'svc-boho-waist',
    name: 'Boho Braid Waist Length',
    category: 'african-braids',
    subcategory: 'boho-braids',
    description: 'Waist-length boho braids with soft texture and a graceful, dimensional finish.',
    startingPrice: 25000,
    priceUnit: 'cents',
    durationMinutes: 360,
    imageUrl: '/services/boho-knotless-braids-blonde.webp',
    imagePosition: 'top center',
    featured: true,
    active: true,
    bookingCount: 109,
  },
  {
    serviceId: 'svc-signature-hairstyles',
    name: 'Signature Hairstyles',
    category: 'african-braids',
    subcategory: 'specialty-braids',
    description: 'Custom statement styles for special occasions, photos, and everyday beauty.',
    startingPrice: 15000,
    priceUnit: 'cents',
    durationMinutes: 180,
    imageUrl: '/services/boho-knotless-braids-copper.webp',
    imagePosition: 'center 22%',
    featured: false,
    active: true,
    bookingCount: 24,
  },
  {
    serviceId: 'svc-professional-hair-braiding',
    name: 'Professional Hair Braiding',
    category: 'african-braids',
    subcategory: 'specialty-braids',
    description: 'Neat, professional braiding for protective styles that are beautiful and durable.',
    startingPrice: 16000,
    priceUnit: 'cents',
    durationMinutes: 210,
    imageUrl: '/services/boho-knotless-braids-golden.webp',
    imagePosition: 'center 22%',
    featured: false,
    active: true,
    bookingCount: 21,
  },

  // ── Natural Hair ────────────────────────────────────────────────────
  {
    serviceId: 'svc-natural-hairstyle',
    name: 'Natural Hairstyle',
    category: 'natural',
    description: 'Shape, define, and style your natural texture with a healthy-hair-first approach.',
    startingPrice: 8500,
    priceUnit: 'cents',
    durationMinutes: 120,
    imageUrl: '/services/natural-hairstyle.webp',
    featured: true,
    active: true,
    bookingCount: 84,
  },
  {
    serviceId: 'svc-silk-press',
    name: 'Silk Press & Styling',
    category: 'natural',
    description: 'A smooth silk press with heat-conscious technique and a soft, luminous finish.',
    startingPrice: 9000,
    priceUnit: 'cents',
    durationMinutes: 120,
    imageUrl: '/services/boho-knotless-braids-golden.webp',
    imagePosition: 'center 22%',
    featured: false,
    active: true,
    bookingCount: 38,
  },
  {
    serviceId: 'svc-protective-styling',
    name: 'Protective Styling',
    category: 'natural',
    description: 'Low-maintenance styles that protect natural hair while keeping your look elevated.',
    startingPrice: 9500,
    priceUnit: 'cents',
    durationMinutes: 120,
    imageUrl: '/services/cornrows-top-bun.webp',
    imagePosition: 'center 18%',
    featured: false,
    active: true,
    bookingCount: 35,
  },
  {
    serviceId: 'svc-deep-treatment',
    name: 'Deep Hair Treatment',
    category: 'natural',
    description: 'Moisture and strengthening care for hair that needs extra softness and support.',
    startingPrice: 5500,
    priceUnit: 'cents',
    durationMinutes: 60,
    imageUrl: '/services/deep-hair-treatment.webp',
    featured: false,
    active: true,
    bookingCount: 18,
  },
  {
    serviceId: 'svc-revitalization',
    name: 'Hair Revitalization Therapy',
    category: 'natural',
    description: 'A restorative service for stressed hair, focused on hydration and manageability.',
    startingPrice: 7000,
    priceUnit: 'cents',
    durationMinutes: 75,
    imageUrl: '/products/hair-revitalization-therapy-product.webp',
    featured: false,
    active: true,
    bookingCount: 29,
  },

  // ── Sew-In & Extensions ─────────────────────────────────────────────
  {
    serviceId: 'svc-sew-in',
    name: 'Sew-In',
    category: 'sew-in',
    description: 'A polished sew-in service with foundation care, blending, and a refined finish.',
    startingPrice: 17500,
    priceUnit: 'cents',
    durationMinutes: 180,
    imageUrl: '/services/sew-in-curly-waves.webp',
    featured: true,
    active: true,
    bookingCount: 121,
  },

  // ── Men ─────────────────────────────────────────────────────────────
  {
    serviceId: 'svc-men-hairstyles',
    name: 'Men Hairstyles',
    category: 'men',
    description: 'Braids, twists, and tailored styles for men with a clean, comfortable experience.',
    startingPrice: 6500,
    priceUnit: 'cents',
    durationMinutes: 90,
    imageUrl: '/services/man-hairstyle-2.webp',
    images: [
      '/services/man-hairstyle-2.webp',
      '/services/man-hairstyle-3.webp',
      '/services/men-hairstyles.webp',
    ],
    imagePosition: 'center 22%',
    featured: true,
    active: true,
    bookingCount: 76,
  },
  {
    serviceId: 'svc-men-dreadlocks',
    name: 'Men Dreadlocks',
    category: 'men',
    description: 'Dreadlock styles for men with expert technique, clean finish, and long-lasting results.',
    startingPrice: 10000,
    priceUnit: 'cents',
    durationMinutes: 120,
    imageUrl: '/services/men-dreadlocks-hairstyles.webp',
    featured: true,
    active: true,
    bookingCount: 58,
  },

  // ── Kids ─────────────────────────────────────────────────────────────
  {
    serviceId: 'svc-kids-hairstyles',
    name: 'Kids Hairstyles',
    category: 'kids',
    description: 'Gentle kids braids and styles designed for comfort, neatness, and confidence.',
    startingPrice: 7500,
    priceUnit: 'cents',
    durationMinutes: 120,
    imageUrl: '/services/kids-cornrows-beads.webp',
    images: [
      '/services/kids-cornrows-beads.webp',
      '/services/kids-twists-bow.webp',
      '/services/kids-box-braids-star-beads.webp',
      '/services/kids-cornrows-color-beads.webp',
      '/services/kids-cornrows-flower-beads.webp',
    ],
    imagePosition: 'top center',
    featured: true,
    active: true,
    bookingCount: 134,
  },
]

export const mockPortfolio: PortfolioItem[] = [
  // ── Knotless Braids ───────────────────────────────────────────────────
  {
    styleId: 'style-knotless-waist',
    title: 'Waist-Length Knotless Braids',
    category: 'knotless',
    imageUrl: '/services/knotless-braids-wavy-ends.webp',
    thumbnailUrl: '/services/knotless-braids-wavy-ends.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-01T12:00:00Z',
  },
  {
    styleId: 'style-boho-braids',
    title: 'Boho Braids with Soft Curls',
    category: 'knotless',
    imageUrl: '/services/boho-knotless-braids-blonde.webp',
    thumbnailUrl: '/services/boho-knotless-braids-blonde.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-02T12:00:00Z',
  },
  {
    styleId: 'style-boho-golden',
    title: 'Boho Knotless Braids — Golden',
    category: 'knotless',
    imageUrl: '/services/boho-knotless-braids-golden.webp',
    thumbnailUrl: '/services/boho-knotless-braids-golden.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-05T12:00:00Z',
  },
  {
    styleId: 'style-boho-copper',
    title: 'Boho Knotless Braids — Copper',
    category: 'knotless',
    imageUrl: '/services/boho-knotless-braids-copper.webp',
    thumbnailUrl: '/services/boho-knotless-braids-copper.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-06T12:00:00Z',
  },
  {
    styleId: 'style-african-braids',
    title: 'African Braids',
    category: 'knotless',
    imageUrl: '/services/african-braids.webp',
    thumbnailUrl: '/services/african-braids.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-07T12:00:00Z',
  },
  {
    styleId: 'style-fulani-braids',
    title: 'Fulani Braids',
    category: 'knotless',
    imageUrl: '/services/fulani-braids.webp',
    thumbnailUrl: '/services/fulani-braids.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-08T12:00:00Z',
  },
  {
    styleId: 'style-miracle-knot',
    title: 'Miracle Knot Hairstyle',
    category: 'knotless',
    imageUrl: '/services/miracle-knot-hairstyle.webp',
    thumbnailUrl: '/services/miracle-knot-hairstyle.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-09T12:00:00Z',
  },
  {
    styleId: 'style-crochet',
    title: 'Crochet Braids',
    category: 'knotless',
    imageUrl: '/services/crochet-hairstyle.webp',
    thumbnailUrl: '/services/crochet-hairstyle.webp',
    featured: false,
    active: true,
    createdAt: '2026-05-10T12:00:00Z',
  },

  // ── Box Braids ────────────────────────────────────────────────────────
  {
    styleId: 'style-jumbo-box-braids',
    title: 'Jumbo Box Braids',
    category: 'box-braids',
    imageUrl: '/services/jumbo-box-braids.webp',
    thumbnailUrl: '/services/jumbo-box-braids.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-11T12:00:00Z',
  },
  {
    styleId: 'style-box-braids',
    title: 'Classic Box Braids',
    category: 'box-braids',
    imageUrl: '/services/box-braids.webp',
    thumbnailUrl: '/services/box-braids.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-12T12:00:00Z',
  },
  {
    styleId: 'style-box-braids-styled',
    title: 'Styled Box Braids Updo',
    category: 'box-braids',
    imageUrl: '/services/box-braids-styled.webp',
    thumbnailUrl: '/services/box-braids-styled.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-13T12:00:00Z',
  },

  // ── Senegalese Twists ─────────────────────────────────────────────────
  {
    styleId: 'style-senegalese-twist',
    title: 'Senegalese Twists',
    category: 'senegalese',
    imageUrl: '/services/senegalese-twist.webp',
    thumbnailUrl: '/services/senegalese-twist.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-14T12:00:00Z',
  },
  {
    styleId: 'style-senegalese-twist-colors',
    title: 'Senegalese Twists with Color',
    category: 'senegalese',
    imageUrl: '/services/senegalese-twist-colors.webp',
    thumbnailUrl: '/services/senegalese-twist-colors.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-15T12:00:00Z',
  },

  // ── Sew-In ────────────────────────────────────────────────────────────
  {
    styleId: 'style-sew-in-layered',
    title: 'Layered Sew-In',
    category: 'sew-in',
    imageUrl: '/services/sew-in-curly-waves.webp',
    thumbnailUrl: '/services/sew-in-curly-waves.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-16T12:00:00Z',
  },

  // ── Natural Hair ──────────────────────────────────────────────────────
  {
    styleId: 'style-natural-hairstyle',
    title: 'Natural Hairstyle',
    category: 'natural',
    imageUrl: '/services/natural-hairstyle.webp',
    thumbnailUrl: '/services/natural-hairstyle.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-17T12:00:00Z',
  },
  {
    styleId: 'style-cornrows-bun',
    title: 'Cornrows into Top Bun',
    category: 'natural',
    imageUrl: '/services/cornrows-top-bun.webp',
    thumbnailUrl: '/services/cornrows-top-bun.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-18T12:00:00Z',
  },

  // ── Kids ──────────────────────────────────────────────────────────────
  {
    styleId: 'style-kids-beads',
    title: 'Kids Braids with Beads',
    category: 'kids',
    imageUrl: '/services/kids-cornrows-beads.webp',
    thumbnailUrl: '/services/kids-cornrows-beads.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-19T12:00:00Z',
  },
  {
    styleId: 'style-kids-twists-bow',
    title: 'Kids Twists with Bow',
    category: 'kids',
    imageUrl: '/services/kids-twists-bow.webp',
    thumbnailUrl: '/services/kids-twists-bow.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-20T12:00:00Z',
  },
  {
    styleId: 'style-kids-star-beads',
    title: 'Kids Box Braids with Star Beads',
    category: 'kids',
    imageUrl: '/services/kids-box-braids-star-beads.webp',
    thumbnailUrl: '/services/kids-box-braids-star-beads.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-21T12:00:00Z',
  },
  {
    styleId: 'style-kids-color-beads',
    title: 'Kids Cornrows with Color Beads',
    category: 'kids',
    imageUrl: '/services/kids-cornrows-color-beads.webp',
    thumbnailUrl: '/services/kids-cornrows-color-beads.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-22T12:00:00Z',
  },
  {
    styleId: 'style-kids-flower-beads',
    title: 'Kids Cornrows with Flower Beads',
    category: 'kids',
    imageUrl: '/services/kids-cornrows-flower-beads.webp',
    thumbnailUrl: '/services/kids-cornrows-flower-beads.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-23T12:00:00Z',
  },

  // ── Men ───────────────────────────────────────────────────────────────
  {
    styleId: 'style-men-hairstyles',
    title: 'Men Hairstyles',
    category: 'men',
    imageUrl: '/services/men-hairstyles.webp',
    thumbnailUrl: '/services/men-hairstyles.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-24T12:00:00Z',
  },
  {
    styleId: 'style-men-hairstyle-2',
    title: 'Men Braided Style',
    category: 'men',
    imageUrl: '/services/man-hairstyle-2.webp',
    thumbnailUrl: '/services/man-hairstyle-2.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-25T12:00:00Z',
  },
  {
    styleId: 'style-men-hairstyle-3',
    title: 'Men Protective Style',
    category: 'men',
    imageUrl: '/services/man-hairstyle-3.webp',
    thumbnailUrl: '/services/man-hairstyle-3.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-26T12:00:00Z',
  },
  {
    styleId: 'style-men-dreadlocks',
    title: 'Men Dreadlocks',
    category: 'men',
    imageUrl: '/services/men-dreadlocks-hairstyles.webp',
    thumbnailUrl: '/services/men-dreadlocks-hairstyles.webp',
    featured: true,
    active: true,
    createdAt: '2026-05-27T12:00:00Z',
  },
]

export const mockReviews: Review[] = [
  {
    reviewId: 'review-1',
    clientName: 'Amara T.',
    rating: 5,
    body: 'Ariane did an incredible job on my knotless braids. Clean parts, zero tension on my scalp, and they lasted almost 8 weeks. People stop me everywhere asking where I go. I won\'t be going anywhere else!',
    serviceName: 'Knotless Braids',
    createdAt: '2026-04-22T12:00:00Z',
    source: 'website',
    status: 'approved',
    featured: true,
  },
  {
    reviewId: 'review-2',
    clientName: 'Kezia M.',
    rating: 5,
    body: 'Brought my daughter in for the first time and she absolutely loved it. Ariane was so patient and gentle with her — my daughter kept saying she wanted to come back every week. The beads were gorgeous!',
    serviceName: 'Kids Hairstyles',
    createdAt: '2026-04-10T12:00:00Z',
    source: 'website',
    status: 'approved',
    featured: true,
  },
  {
    reviewId: 'review-3',
    clientName: 'Nadia B.',
    rating: 5,
    body: 'Best boho braids I have ever had, and I have been natural for 10 years. The texture was perfect, the length was flawless, and she really listened to exactly what I wanted. 10 out of 10, no question.',
    serviceName: 'Boho Braid Waist Length',
    createdAt: '2026-03-28T12:00:00Z',
    source: 'website',
    status: 'approved',
    featured: true,
  },
  {
    reviewId: 'review-4',
    clientName: 'Imani R.',
    rating: 5,
    body: 'I had a full sew-in done and I am obsessed with the result. It looks completely natural and lays so flat. My coworkers thought I just cut and colored my hair. The salon is clean, welcoming, and professional.',
    serviceName: 'Sew-In',
    createdAt: '2026-03-15T12:00:00Z',
    source: 'website',
    status: 'approved',
    featured: false,
  },
  {
    reviewId: 'review-5',
    clientName: 'Zora A.',
    rating: 5,
    body: 'My hair has never felt so healthy. Ariane spent real time understanding my hair before touching it. The deep treatment plus protective styling combo was exactly what I needed. Highly recommend.',
    serviceName: 'Protective Styling',
    createdAt: '2026-02-20T12:00:00Z',
    source: 'website',
    status: 'approved',
    featured: false,
  },
  {
    reviewId: 'review-6',
    clientName: 'Fatou D.',
    rating: 5,
    body: 'Came in for African braids and left feeling like royalty. The parts are so clean, the install was painless, and the style held up perfectly through two washes. Grace Hair Beauty is a true gem in Indianapolis.',
    serviceName: 'African Braids',
    createdAt: '2026-02-05T12:00:00Z',
    source: 'website',
    status: 'approved',
    featured: false,
  },
]

export const mockReviewAggregates: ReviewAggregates = {
  averageRating: 5.0,
  totalCount: 6,
}
